FROM google/cloud-sdk:latest

WORKDIR /app

COPY scripts/ ./scripts/
COPY .github/workflows/deploy-cloud-run.yml ./.github/workflows/

RUN chmod +x scripts/**/*.sh

ENTRYPOINT ["scripts/google-cloud/setup-project.sh"]
